name: Deploy Web

on:
  push:
    branches:
      - master

jobs:
  deploy_web:
    name: Deploy web to EAS Hosting
    type: deploy
    environment:
      name: production
    params:
      prod: true
