name: Release iOS

on:
  push:
    branches:
      - release-ios

jobs:
  build_ios:
    name: Build iOS (production)
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    name: Submit to App Store Connect
    type: submit
    needs: [build_ios]
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
