-- Set image_url + image_status = 'approved' for all seeded equipment.
-- Images were pre-converted to WebP (800×600 max, q82) and uploaded to Supabase Storage.

-- Grinders
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/baratza-encore-esp.webp',        image_status = 'approved' where brand = 'Baratza'         and model = 'Encore ESP';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/baratza-virtuoso-plus.webp',      image_status = 'approved' where brand = 'Baratza'         and model = 'Virtuoso+';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/baratza-sette-270wi.webp',        image_status = 'approved' where brand = 'Baratza'         and model = 'Sette 270Wi';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/baratza-vario-plus.webp',         image_status = 'approved' where brand = 'Baratza'         and model = 'Vario+';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/eureka-mignon-specialita.webp',   image_status = 'approved' where brand = 'Eureka'          and model = 'Mignon Specialita';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/eureka-mignon-libra.webp',        image_status = 'approved' where brand = 'Eureka'          and model = 'Mignon Libra';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/eureka-mignon-filtro.webp',       image_status = 'approved' where brand = 'Eureka'          and model = 'Mignon Filtro';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/niche-zero.webp',                 image_status = 'approved' where brand = 'Niche'           and model = 'Zero';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/niche-duo.webp',                  image_status = 'approved' where brand = 'Niche'           and model = 'Duo';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/fellow-ode-gen-2.webp',           image_status = 'approved' where brand = 'Fellow'          and model = 'Ode Gen 2';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/fellow-opus.webp',                image_status = 'approved' where brand = 'Fellow'          and model = 'Opus';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/comandante-c40-mk4.webp',         image_status = 'approved' where brand = 'Comandante'      and model = 'C40 MK4';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/1zpresso-j-ultra.webp',           image_status = 'approved' where brand = '1Zpresso'        and model = 'J-Ultra';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/1zpresso-k-ultra.webp',           image_status = 'approved' where brand = '1Zpresso'        and model = 'K-Ultra';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/1zpresso-q2-s.webp',              image_status = 'approved' where brand = '1Zpresso'        and model = 'Q2 S';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/weber-workshops-key.webp',        image_status = 'approved' where brand = 'Weber Workshops' and model = 'Key';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/df-df64-gen-2.webp',              image_status = 'approved' where brand = 'DF'              and model = 'DF64 Gen 2';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/df-df83.webp',                    image_status = 'approved' where brand = 'DF'              and model = 'DF83';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/lagom-p64.webp',                  image_status = 'approved' where brand = 'Lagom'           and model = 'P64';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/lagom-p100.webp',                 image_status = 'approved' where brand = 'Lagom'           and model = 'P100';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/kinu-m47-classic.webp',           image_status = 'approved' where brand = 'Kinu'            and model = 'M47 Classic';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/mahlkonig-ek43-s.webp',           image_status = 'approved' where brand = 'Mahlkonig'       and model = 'EK43 S';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/rancilio-rocky.webp',              image_status = 'approved' where brand = 'Rancilio'        and model = 'Rocky';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/breville-smart-grinder-pro.webp', image_status = 'approved' where brand = 'Breville'        and model = 'Smart Grinder Pro';
update public.grinders set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/grinders/lelit-fred-pl043.webp',           image_status = 'approved' where brand = 'Lelit'           and model = 'Fred PL043';

-- Brew Machines
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/breville-bambino-plus.webp',             image_status = 'approved' where brand = 'Breville'        and model = 'Bambino Plus';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/breville-barista-express.webp',          image_status = 'approved' where brand = 'Breville'        and model = 'Barista Express';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/breville-barista-pro.webp',              image_status = 'approved' where brand = 'Breville'        and model = 'Barista Pro';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/breville-oracle-touch.webp',             image_status = 'approved' where brand = 'Breville'        and model = 'Oracle Touch';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/breville-precision-brewer.webp',         image_status = 'approved' where brand = 'Breville'        and model = 'Precision Brewer';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/delonghi-dedica-arte-ec885.webp',        image_status = 'approved' where brand = 'De''Longhi'      and model = 'Dedica Arte EC885';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/delonghi-la-specialista-arte-ec9155.webp' , image_status = 'approved' where brand = 'De''Longhi'  and model = 'La Specialista Arte EC9155';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/delonghi-magnifica-evo.webp',             image_status = 'approved' where brand = 'De''Longhi'      and model = 'Magnifica Evo';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/delonghi-dinamica-plus.webp',             image_status = 'approved' where brand = 'De''Longhi'      and model = 'Dinamica Plus';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/rancilio-silvia-pro-x.webp',             image_status = 'approved' where brand = 'Rancilio'        and model = 'Silvia Pro X';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/rancilio-silvia-v6.webp',                image_status = 'approved' where brand = 'Rancilio'        and model = 'Silvia V6';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/lelit-bianca-v3.webp',                   image_status = 'approved' where brand = 'Lelit'           and model = 'Bianca V3';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/lelit-mara-x-v2.webp',                   image_status = 'approved' where brand = 'Lelit'           and model = 'Mara X V2';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/ecm-synchronika.webp',                   image_status = 'approved' where brand = 'ECM'             and model = 'Synchronika';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/profitec-pro-600.webp',                  image_status = 'approved' where brand = 'Profitec'        and model = 'Pro 600';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/la-marzocco-linea-mini.webp',            image_status = 'approved' where brand = 'La Marzocco'     and model = 'Linea Mini';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/la-marzocco-gs3.webp',                   image_status = 'approved' where brand = 'La Marzocco'     and model = 'GS/3';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/decent-espresso-de1pro.webp',            image_status = 'approved' where brand = 'Decent Espresso' and model = 'DE1Pro';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/jura-e8.webp',                           image_status = 'approved' where brand = 'Jura'            and model = 'E8';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/jura-z10.webp',                          image_status = 'approved' where brand = 'Jura'            and model = 'Z10';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/philips-ep3347-series-3300.webp',        image_status = 'approved' where brand = 'Philips'         and model = 'EP3347 Series 3300';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/nespresso-vertuo-next.webp',             image_status = 'approved' where brand = 'Nespresso'       and model = 'Vertuo Next';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/nespresso-essenza-mini.webp',            image_status = 'approved' where brand = 'Nespresso'       and model = 'Essenza Mini';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/technivorm-moccamaster-kbt.webp',        image_status = 'approved' where brand = 'Technivorm'      and model = 'Moccamaster KBT';
update public.brew_machines set image_url = 'https://rmudbcyozoddlsxklxhq.supabase.co/storage/v1/object/public/equipment-images/machines/bonavita-bv1901ts.webp',                 image_status = 'approved' where brand = 'Bonavita'        and model = 'BV1901TS';
